# Generated by Django 6.0.1 on 2026-03-11 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_is_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='timezone',
            field=models.CharField(default='UTC', max_length=50),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
