# Generated by Django 6.0.1 on 2026-03-12 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_avatar'),
        ('users', '0004_alter_user_email'),
    ]

    operations = [
    ]
