# Generated by Django 6.0.1 on 2026-03-12 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatting', '0003_chat_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='chat',
        ),
        migrations.RemoveField(
            model_name='message',
            name='author',
        ),
        migrations.DeleteModel(
            name='Chat',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
