# Generated by Django 6.0.1 on 2026-03-12 06:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatting', '0002_message_image_alter_message_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
