# Generated by Django 6.0.1 on 2026-03-03 12:58

import chats.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0005_chat_chatname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='id',
            field=models.UUIDField(default=chats.models.generate_uuid, primary_key=True, serialize=False),
        ),
    ]
