# Generated by Django 6.0.1 on 2026-03-10 11:41

import chats.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0006_alter_chat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='id',
            field=models.CharField(default=chats.models.generate_uuid, max_length=36, primary_key=True, serialize=False),
        ),
    ]
