# Generated by Django 6.0.1 on 2026-02-11 05:56

import uuid
from django.db import migrations, models
from django.conf import settings


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='server_avatars/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=models.CASCADE, related_name='owned_servers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Сервер',
                'verbose_name_plural': 'Серверы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServerData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(default=dict)),
            ],
        ),
    ]
