# Generated by Django 6.0.1 on 2026-04-07 06:26

import chats.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.CharField(default=chats.models.generate_uuid, max_length=36, primary_key=True, serialize=False)),
                ('number', models.CharField(default=chats.models.unic_number, max_length=6)),
                ('max_chaters', models.IntegerField(default=12)),
                ('done', models.BooleanField(default=False)),
                ('started', models.BooleanField(default=False)),
                ('chatName', models.CharField(default='test_chat', max_length=150)),
                ('chat_avatar', models.ImageField(default='avatars/def.jpg', upload_to='avatars/')),
                ('is_private', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ChatData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(default=dict)),
            ],
        ),
    ]
