# Generated by Django 6.0.1 on 2026-03-12 16:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='server_avatars/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_servers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Сервер',
                'verbose_name_plural': 'Серверы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServerMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Владелец'), ('admin', 'Администратор'), ('member', 'Участник')], default='member', max_length=10)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='server_members', to='servers.server')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='server_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Участник сервера',
                'verbose_name_plural': 'Участники сервера',
                'unique_together': {('server', 'user')},
            },
        ),
        migrations.AddField(
            model_name='server',
            name='members',
            field=models.ManyToManyField(related_name='servers', through='servers.ServerMember', to=settings.AUTH_USER_MODEL),
        ),
    ]
