# Generated by Django 6.0.1 on 2026-04-21 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0002_server_is_public'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servermember',
            options={'verbose_name': 'Владелец сервера', 'verbose_name_plural': 'Владельцы серверов'},
        ),
        migrations.AlterField(
            model_name='server',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
