# Generated by Django 6.0.1 on 2026-04-28 04:42

import servers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0003_alter_servermember_options_alter_server_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='max_members',
            field=models.PositiveIntegerField(default=100, help_text='Максимальное количество участников'),
        ),
        migrations.AlterField(
            model_name='server',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=servers.models.server_avatar_upload_path),
        ),
    ]
