# Generated by Django 6.0.1 on 2026-04-28 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0004_server_max_members_alter_server_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='max_members',
            field=models.PositiveIntegerField(default=12, help_text='Максимальное количество участников'),
        ),
    ]
