# Generated by Django 6.0.1 on 2026-04-28 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0005_alter_server_max_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='max_members',
            field=models.PositiveIntegerField(default=2, help_text='Максимальное количество участников (макс. 12)'),
        ),
    ]
